# Generated by Django 5.2.8 on 2025-11-09 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('REQUEST', 'Request'), ('SYSTEM', 'System'), ('WORKFLOW', 'Workflow')], default='SYSTEM', max_length=20)),
                ('event', models.CharField(choices=[('REQUEST_CREATED', 'Request created'), ('REQUEST_ACCEPTED', 'Request accepted'), ('REQUEST_COMPLETED', 'Request completed'), ('REQUEST_CANCELLED', 'Request cancelled'), ('GENERIC', 'Generic message')], default='GENERIC', max_length=40)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reference_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.servicerequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event', 'reference_request'), name='unique_notification_per_event')],
            },
        ),
    ]
